// Lista de países (ISO 3166-1 alpha-2) para el selector de "País de
// residencia" de Mi perfil (Fase 9, 2026-09-07) — taxonomía universal
// fija, mismo criterio que `language`/`professional_level` en
// schema.sql: no es configuración de negocio de la cuenta, así que vive
// como constante aquí, no como tabla de Supabase (convención 1 de
// CLAUDE.md se aplica a datos de NEGOCIO, no a un estándar internacional
// que no cambia).
export const COUNTRIES = [
  { code: "ES", es: "España", en: "Spain" },
  { code: "MX", es: "México", en: "Mexico" },
  { code: "AR", es: "Argentina", en: "Argentina" },
  { code: "CO", es: "Colombia", en: "Colombia" },
  { code: "CL", es: "Chile", en: "Chile" },
  { code: "PE", es: "Perú", en: "Peru" },
  { code: "VE", es: "Venezuela", en: "Venezuela" },
  { code: "EC", es: "Ecuador", en: "Ecuador" },
  { code: "GT", es: "Guatemala", en: "Guatemala" },
  { code: "CU", es: "Cuba", en: "Cuba" },
  { code: "BO", es: "Bolivia", en: "Bolivia" },
  { code: "DO", es: "República Dominicana", en: "Dominican Republic" },
  { code: "HN", es: "Honduras", en: "Honduras" },
  { code: "PY", es: "Paraguay", en: "Paraguay" },
  { code: "SV", es: "El Salvador", en: "El Salvador" },
  { code: "NI", es: "Nicaragua", en: "Nicaragua" },
  { code: "CR", es: "Costa Rica", en: "Costa Rica" },
  { code: "PA", es: "Panamá", en: "Panama" },
  { code: "UY", es: "Uruguay", en: "Uruguay" },
  { code: "PR", es: "Puerto Rico", en: "Puerto Rico" },
  { code: "US", es: "Estados Unidos", en: "United States" },
  { code: "CA", es: "Canadá", en: "Canada" },
  { code: "BR", es: "Brasil", en: "Brazil" },
  { code: "GB", es: "Reino Unido", en: "United Kingdom" },
  { code: "IE", es: "Irlanda", en: "Ireland" },
  { code: "FR", es: "Francia", en: "France" },
  { code: "DE", es: "Alemania", en: "Germany" },
  { code: "IT", es: "Italia", en: "Italy" },
  { code: "PT", es: "Portugal", en: "Portugal" },
  { code: "NL", es: "Países Bajos", en: "Netherlands" },
  { code: "BE", es: "Bélgica", en: "Belgium" },
  { code: "CH", es: "Suiza", en: "Switzerland" },
  { code: "AT", es: "Austria", en: "Austria" },
  { code: "SE", es: "Suecia", en: "Sweden" },
  { code: "NO", es: "Noruega", en: "Norway" },
  { code: "DK", es: "Dinamarca", en: "Denmark" },
  { code: "FI", es: "Finlandia", en: "Finland" },
  { code: "PL", es: "Polonia", en: "Poland" },
  { code: "GR", es: "Grecia", en: "Greece" },
  { code: "CZ", es: "Chequia", en: "Czechia" },
  { code: "RO", es: "Rumanía", en: "Romania" },
  { code: "HU", es: "Hungría", en: "Hungary" },
  { code: "IS", es: "Islandia", en: "Iceland" },
  { code: "MT", es: "Malta", en: "Malta" },
  { code: "CY", es: "Chipre", en: "Cyprus" },
  { code: "HR", es: "Croacia", en: "Croatia" },
  { code: "TR", es: "Turquía", en: "Turkey" },
  { code: "EG", es: "Egipto", en: "Egypt" },
  { code: "MA", es: "Marruecos", en: "Morocco" },
  { code: "ZA", es: "Sudáfrica", en: "South Africa" },
  { code: "AE", es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { code: "IL", es: "Israel", en: "Israel" },
  { code: "TH", es: "Tailandia", en: "Thailand" },
  { code: "PH", es: "Filipinas", en: "Philippines" },
  { code: "ID", es: "Indonesia", en: "Indonesia" },
  { code: "MY", es: "Malasia", en: "Malaysia" },
  { code: "VN", es: "Vietnam", en: "Vietnam" },
  { code: "JP", es: "Japón", en: "Japan" },
  { code: "KR", es: "Corea del Sur", en: "South Korea" },
  { code: "CN", es: "China", en: "China" },
  { code: "IN", es: "India", en: "India" },
  { code: "AU", es: "Australia", en: "Australia" },
  { code: "NZ", es: "Nueva Zelanda", en: "New Zealand" },
  { code: "FJ", es: "Fiyi", en: "Fiji" },
  { code: "MV", es: "Maldivas", en: "Maldives" },
  { code: "OTHER", es: "Otro", en: "Other" },
];
